addon/popup.js

fix popup error missing key

---

CHANGES.md
addon/data-import.js

auto detect import externalId field

---

CHANGES.md
README.md
addon/button.css
addon/data-export.js

remove comment in query

---

CHANGES.md
addon/data-export.js
addon/options.js

Formatsoql

---

CHANGES.md
addon/data-export.js
addon/data-load.js
addon/log.js

export : download csv #26

---

addon/data-import.css
addon/data-import.js

helper and toggle format button

---

addon/apex-runner.css
addon/apex-runner.js

apex: improove suggestion

---

addon/data-load.js
addon/inspect.js

Closepopup

---

addon/apex-runner.js
addon/data-export.js

autoident on new line

---

addon/apex-runner.js
addon/data-export.js
addon/data-load.js

indent selection with tab/shift tab

---

addon/apex-runner.js
addon/data-export.js
addon/data-load.js

add closing char on (, [, ", ' and delete indent

---

.eslintrc.js
CHANGES.md
addon/popup.js

Escape will close popup
I also fix eslint warning

fix #71 closePopup

---

addon/apex-runner.js
addon/data-export.css
addon/data-export.js
addon/data-load.js

auto suggest over editor

---

addon/apex-runner.css
addon/apex-runner.js
addon/data-export.css
addon/data-load.js

Editorapex

---

addon/button.css

fix #77 resize popup window

---

addon/button.css
addon/button.js
addon/popup.js

fix #86 show flow details

---

addon/popup.js

refactor composite request

---

CHANGES.md

Add changes

---

CHANGES.md
addon/data-import.js
addon/data-load.css
addon/data-load.js
addon/manifest-template.json
addon/manifest.json

fix #48 compare row when 2 displayed

---

addon/setup-links.js

Fix #108 handle address field properly in inspect

---

CHANGES.md
addon/log.css
addon/log.js

fix #105 replace id by name or label in profiler

fix #105 replace id by name or label in profiler

---

addon/popup.js
addon/streaming.js

push event

---

addon/data-export.js
addon/options.js

Fix double serialisation json and dlimiter

---

addon/log.js

fix #115 color on chart

---

addon/log.js

add mesure on flamgraph

---

addon/data-export.js
addon/data-load.css
addon/data-load.js

#126 : suggestion on data export edit

---

addon/inspect.js

add roll up summary info

---

addon/apex-runner.js
addon/data-export.css
addon/data-export.js
addon/data-import.css
addon/data-import.js
addon/log.css
addon/log.js
addon/options.js

#152 : option link from page

---

addon/popup.js

#155: fix link plateform event

---

addon/data-export.js

fix name of saved query in list

---

addon/data-import.js
addon/manifest-template.json
addon/manifest.json
addon/popup.js

Iss72 165 fix tokn generation issue

---

addon/inspector.js

retry token with background service before hard failing

---

addon/data-export.js
addon/data-load.js

keep state of cells with scroll or loading data

---

addon/data-export.js

Graphql in export

---

addon/button.css
addon/button.js
addon/data-export.js
addon/dependency.html
addon/dependency.js
addon/manifest-template.json
addon/manifest.json
addon/popup.js

dependency button on flow

---

addon/streaming.css
addon/streaming.html
addon/streaming.js

streaming: format json

---

addon/data-export.js
addon/data-import.js
addon/options.js

Support decimal format comma with an option on import and export
